### ISSUE TITLE
点击启动dosbox没反应

### ISSUE THREAD

**Issue by LittleNoob2333** [Woodykaixa/masm-code#12]
大佬我按照教程点击启动dosbox，但是没反应，是不是不能再win10系统使用啊

**Comment by Woodykaixa** [comment]
closed issues里有同样的问题，你按照他的操作做一遍，不行再说

**Comment by LittleNoob2333** [comment]
我尝试了替换dosbox.exe，删除0kb文件然后重启vscode，但还是不行，枯了

**Comment by Woodykaixa** [comment]
那我也没办法了，毕竟dosbox也不是我写的

**Comment by pjx206** [comment]
我知道我知道！我发现重启n次还是那个目录底下的东西都是0kb。解决方法是克隆这个仓库，把/Dosbox和/Dosbos/bin底下的替换掉那些0kb的文件就行。
![image](https://user-images.githubusercontent.com/31790712/79712844-9c12c000-82fe-11ea-869a-d51f9e920279.png)

**Comment by LittleNoob2333** [comment]
好了好了，感谢大佬，请接受卑微菜鸡跪拜，还有kaixa学长，tql！

**Comment by Woodykaixa** [comment]
感谢就算了，duck不必。我也是菜鸡.
