### ISSUE TITLE
关于"lib"的高亮显示问题

### ISSUE THREAD

**Issue by XuYangYu233** [Woodykaixa/masm-code#15]
rt。输入“INCLUDE MACROLIB.LIB”时，“MACROLIB.LIB”这个单词的“MACRO”部分未显示高亮，“LIB.LIB”部分全部高亮，整体上较为不协调

**Comment by Woodykaixa** [comment]
可能是因为macro是关键字的原因。不过你这个用法超出了我们学校所讲的范围，我不清楚这个东西，也不会去修复这个问题。
