### ISSUE TITLE
dosbox 调整窗口大小没反应

### ISSUE THREAD

**Issue by nosnakeob** [Woodykaixa/masm-code#17]
如图
![image](https://user-images.githubusercontent.com/47769817/81468706-c4ae1b80-9213-11ea-82b9-d12acda25ffd.png)

![image](https://user-images.githubusercontent.com/47769817/81468721-e0192680-9213-11ea-8cb3-a1d3a80de1e6.png)

**Comment by Woodykaixa** [comment]
设置修改后重启一下vscode试试？

**Comment by nosnakeob** [comment]
> 设置修改后重启一下vscode试试？

原来我在其他地方也安装了dosbox，删除之后再重启就成功了。不过我发现修改设置之后直接启动dosbox没有效果，只有重启才有效，是不是出现bug了？

**Comment by Woodykaixa** [comment]
我也不知道为什么，我是照着官网的说明写的，但是设置就只能重启生效，我也想知道那些插件都是怎么做到的

**Comment by nosnakeob** [comment]
> 我也不知道为什么，我是照着官网的说明写的，但是设置就只能重启生效，我也想知道那些插件都是怎么做到的

那没办法了
