### ISSUE TITLE
DOSBox无法启动

### ISSUE THREAD

**Issue by MycroftCooper** [Woodykaixa/masm-code#2]
在VSCODE中使用两个代码都无法启动DOSBox，而在C:\Users\XXX\AppData\Roaming\Code\User\globalStorage\kaixa.masm-code目录下找到DOSBox.exe发现并不是0KB，点击运行系统提示“此应用无法在你的电脑上运行”。

**Comment by Woodykaixa** [comment]
那dosbox文件大小是多少啊？会不会没下载完？你和release里面的比一下

**Comment by MycroftCooper** [comment]
> 那dosbox文件大小是多少啊？会不会没下载完？你和释放里面的比一下

我对比了我和官网下载的DOSBox文件发现会小很多，于是我将官网下载的DOSBox.exe执行文件替换到了kaixa.masm-code目录下，现在可以通过vscode代码运行DOSBox了，但是又有了新的报错，报错内容为error A4910: cannot open file: X:\ML.err。我在目录下寻找，发现是有ML.exe的，但是没有ML.err

**Comment by Woodykaixa** [comment]
那看来是由于某种原因下载终止了，但是我只写了检查文件是否存在的代码，文件大小没有比对。ml.err没有是因为我写这个扩展的时候我还没有写过汇编，不知道要用到这个文件，后来我发现只要代码没有错好像也用不到这个文件，所以目前还没有加上。

**Comment by MycroftCooper** [comment]
> 那看来是由于某种原因下载终止了，但是我只写了检查文件是否存在的代码，文件大小没有比对。ml.err没有是因为我写这个扩展的时候我还没有写过汇编，不知道要用到这个文件，后来我发现只要代码没有错好像也用不到这个文件，所以目前还没有加上。

我百度下载了ml.err文件放在目录下之后此报错消失，又出现了新的报错，这次是fatal error A1000: can not open file

**Comment by Woodykaixa** [comment]
你有打开.asm文件吗？编译运行的指令要打开一个扩展名是asm的文件，然后编译这个文件。

**Comment by MycroftCooper** [comment]
> 你有打开.asm文件吗？编译运行的指令要打开一个扩展名是asm的文件，然后编译这个文件。

有的，我发现是我的.asm文件名称过长的原因，helloworld超过了9个字节，改成hello后此报错消失，但又出现了新的报错LINK:fatal error L1002：Z2：unrecognized option name

**Comment by Woodykaixa** [comment]
这是代码的问题吧？

**Comment by MycroftCooper** [comment]
DSEG    SEGMENT
MESS    DB   'Hello,World!' ,0DH,0AH,24H
DSEG    ENDS
  
SSEG    SEGMENT PARA STACK 
        DW  256 DUP(?)
SSEG    ENDS
CSEG    SEGMENT
        ASSUME  CS:CSEG,DS:DSEG
BEGIN:  MOV AX,DSEG
        MOV DS,AX
        MOV DX,OFFSET MESS
        MOV AH,9

        INT 21H
         MOV AH,4CH
         INT 21H
CSEG    ENDS
         END  BEGIN
应该.....没有问题吧

**Comment by Woodykaixa** [comment]
好像是说链接器没有z2这个选项

**Comment by MycroftCooper** [comment]
> 好像是说链接器没有z2这个选项

这个......我就百度不到了.......代码里也没有z2相关的东西......

**Comment by MycroftCooper** [comment]
同志，没有问题了，全都解决了。
非常感谢你制作的插件！真的帮了很大的忙！让小白入门汇编轻松了很多！

**Comment by IsaacJia0208** [comment]
> 同志，没有问题了，全都解决了。
> 非常感谢你制作的插件！真的帮了很大的忙！让小白入门汇编轻松了很多！

您好，请问您是怎么装好的啊，我的一直打不开Dosbox，也都不是0kb,能替换的也替换了
