### ISSUE TITLE
非法指令问题/打不开DOSbox

### ISSUE THREAD

**Issue by IsaacJia0208** [Woodykaixa/masm-code#20]
同之前的问题一样，该设置的替换的也都替换了，没有0k的文件，DOS、link、就是打不开DOSbox，后来手动打开dosbox后发现从vscode里面输入的指令都有显示，MOUNT装载成功，但ML指令和后面的运行exe指令都说illegal command，没有生成obj文件和exe文件

**Comment by Woodykaixa** [comment]
你看一下是不是因为ml.exe

**Comment by IsaacJia0208** [comment]
> 你看一下是不是因为ml.exe

啥意思😢

**Comment by IsaacJia0208** [comment]
> 你看一下是不是因为ml.exe

我的ml.exe文件在200k左右，但是单独双击就说版本不一致，让我重新找适合版本，但之前用MASM for windows时ML.exe也不能被单独打开

**Comment by IsaacJia0208** [comment]
.486  
DATA 	SEGMENT 	USE16  
BUF		DB 'ABCD'  
COUNT	EQU $-BUF  
DATA 	ENDS  
CODE 	SEGMENT 	USE16  
ASSUME CS:CODE,DS:DATA  
BEG:  
    MOV 	AX,	DATA  
    MOV 	DS,	AX  
    MOV 	BL,	0    ;计数  
    MOV	SI,	0  
    MOV 	CX,	COUNT  
AGA:  
    CMP 	BUF[SI],		42H  
    JB 		LAST    ;低于转移  
    CMP 	BUF[SI],45H  
    JA 		LAST    ;高于转移  
    INC		BL  
LAST:  
	INC SI  
    LOOP 	AGA  
    MOV	CX,		8  

M2:  
    TEST 	BL,		80H  
    JNZ 	M3  
    MOV 	DL,		'0'  
    MOV 	AH,		02H  
    INT 	21H  
    JMP 	M4  
M3:  
    MOV 	DL,		'1'  
    MOV 	AH,		02H  
    INT 	21H  
M4:  
    SHL 	BL,		1  
    LOOP 	M2  
    MOV 	AH,		4CH  
    INT 	21H  
CODE 	ENDS  
    	END	 BEG

**Comment by Woodykaixa** [comment]
> > 你看一下是不是因为ml.exe
> 
> 我的ml.exe文件在200k左右，但是单独双击就说版本不一致，让我重新找适合版本，但之前用MASM for windows时ML.exe也不能被单独打开

我的是380kb

**Comment by Woodykaixa** [comment]
关于插件打不开dosbox的问题，你试试直接用powershell可以打开dosbox吗

**Comment by Woodykaixa** [comment]
https://github.com/Woodykaixa/masm-code/releases/tag/Masm%26DOSBox
插件是从这里下载的组件，你自己用浏览器下载一下替换试试

**Comment by IsaacJia0208** [comment]
谢谢，我觉得可能是因为我的cmd路径里有空格，我想请问打开dosbox的vscode代码在哪？网上说给路径加上双引号就能用cmd打开了

**Comment by IsaacJia0208** [comment]
或者我可以直接把globalStorage放到没有空格的路径里，请问怎么修改VScode代码啊

**Comment by Woodykaixa** [comment]
> 谢谢，我觉得可能是因为我的cmd路径里有空格，我想请问打开dosbox的vscode代码在哪？网上说给路径加上双引号就能用cmd打开了

https://github.com/Woodykaixa/masm-code/pull/18
可是这个pull request已经修过mount指令空格的问题了

**Comment by Woodykaixa** [comment]
> 或者我可以直接把globalStorage放到没有空格的路径里，请问怎么修改VScode代码啊

fork代码，然后clone到本地，改好了发pull request

**Comment by IsaacJia0208** [comment]
> > 或者我可以直接把globalStorage放到没有空格的路径里，请问怎么修改VScode代码啊
> 
> fork代码，然后clone到本地，改好了发pull request

绝了，我放弃了
