### ISSUE TITLE
ADD support custom path, TASM,problem match

### ISSUE THREAD

**Issue by xsro** [Woodykaixa/masm-code#22]
Nice 
太棒了，我也有类似的想法，但是我不会写js，更不会ts，所以不会写VSCode拓展

## 建议

- ⭐ 支持可以自定义dosbox，masm，tasm路径，这样就可以手动下载了，再关联进去了，也可以作为环境变量可以让Code Runner调用（我猜的）
- 支持长文件名
- 增加对TASM的支持
- 输出问题输出

## 推荐

推荐使用`start/min/wait dosbox`代替`dosbox -noconsole`这样不会生成多余文件

## 其他
我是使用终端任务的方法来实现这些功能的，如果能集成到拓展中当然更好了
推荐一下我的仓库，就是一些自定义任务 [my repo](https://github.com/xsro/VSC-ASMtasks)

**Comment by Woodykaixa** [comment]
因为一开始这个扩展写来是对付我校的汇编课的作业和考试的，所以dosbox和masm是肯定不会变的。虽然我也有关于这个扩展的更多想法，现在这个课程结束了，我现在的兴趣在别的方面，所以这个扩展暂时应该是不会更新了。

**Comment by xsro** [comment]
理解
