### ISSUE TITLE
manjaro kde上无法启动dosbox-x（dosbox的一个分支版本）

### ISSUE THREAD

**Issue by Jontyshaw** [Woodykaixa/masm-code#24]
环境：Manjaro Kde 和dosbox-x
问题描述：启动dosbox命令无法启动dosbox-x
建议：增加一个扩展设置项（用来启动类似于dosbox-x、dosemu的模拟器），具体启动命令提供一个格式
这个是dosbox-x项目的地址（https://github.com/joncampbell123/dosbox-x）
![Screenshot_20200724_170454](https://user-images.githubusercontent.com/34794522/88376359-cc6f6c00-cdcf-11ea-8881-6c899ce33973.png)

**Comment by xsro** [comment]
这个插件主要面向的是windows用户，所以没有对linux等其他系统进行优化，如果你喜欢的话，可以自己配置vscode终端任务来实现调用dosbox-x相关功能,当然也可以修改一下插件

可以看一下这个
