### ISSUE TITLE
CTRL+SHIFT+P doesn't start dosbox

### ISSUE THREAD

**Issue by molitona** [Woodykaixa/masm-code#33]
Hi, I'm using masm-code on linux. I've dosbox installed and CTRL+SHIFT+P doesn't start dosbox ? what's the matter ?

**Comment by Woodykaixa** [comment]
I have stopped supporting this extension.  Try [masm-tasm](https://github.com/dosasm/masm-tasm). It looks better than mine, and author is active on maintenance.
