### ISSUE TITLE
与知乎上的那个在VSC上运行MASM汇编的文章里使用的方法兼容性不太行

### ISSUE THREAD

**Issue by XuYangYu233** [Woodykaixa/masm-code#4]
https://zhuanlan.zhihu.com/p/105268949这是链接。当然，解决方法是把插件的package.json里的几处asm和Assembly全部换成masm，这样就可以和code-runner及MASM插件一起愉快地使用了

**Comment by Woodykaixa** [comment]
666. 主要是我们学校开的汇编课考试要用dosbox，所以我这个扩展才这么搞的

**Comment by wz1765** [comment]
我本来准备达到在vsc里面debug的效果，但是最后只实现了编译所以是半成品啦hhhhh

**难点主要是如何像qemu一样在某一个端口运行，并且暂停等待调试，然后用gdb远程调试（不过这里还有的难点就是vsc里面对于汇编的断点支持依然需要加一个插件，就像Breakpoint for Fortran一样）**

现在我准备的解决方案是这个插件（提供补全），open插件（利用外部程序打开），然后用emu8086默认打开asm和inc文件，这样编辑完文件，右键文件，外部程序打开，然后就可以在emu8086里面愉快debug加断点啦。
**在某种意义上再实现一个adapter和breakpoint的插件相当于重新写一个emu8086的低配版，可以但没有必要**

我既然选择用vsc，目的是更舒服地写代码和debug而不影响心情，考试的话主要是背背背啦~如果非要用dosbox的话那么不如直接用EDIT这样还保证一直在同一个环境。

**Comment by Woodykaixa** [comment]
因为我们考试只有上机没有笔试，上机环境是dosbox，调试也只能用debug.exe。
