### ISSUE TITLE
设置dosbox无控制台启动

### ISSUE THREAD

**Issue by QianxiL** [Woodykaixa/masm-code#9]
你好，可以在启动dosbox的代码中加入" -noconsole"来关闭dosbox背后那个控制台，用起来更舒服一点，个人亲测可用

**Comment by wz1765** [comment]
a batch file based support may be added in the future, in which you could add customize option to MASM and LINK, along with some gdb support.

> 你好，可以在启动dosbox的代码中加入" -noconsole"来关闭dosbox背后那个控制台，用起来更舒服一点，个人亲测可用

**Comment by LittleNoob2333** [comment]
大佬，请问一下为啥我点那个启用dosbox没有反应啊

**Comment by Woodykaixa** [comment]
功能加上了，在设置里，但是每次修改设置以后要重启才行（我是按照官方文档来的，但是不重启vscode设置不会变，我也不知道为什么）
